language: node_js
sudo: false
dist: trusty
node_js:
  - "7"

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build

cache:
  directories:
    - node_modules

before_deploy:
  - cd ./build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  repo: MaxFlower/maxflower.github.io
  on:
    branch: master
